# -*- coding: utf-8 -*-
"""lesson2_21-04-2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ju045oV_S7dlF7pszrvG0zwyyCqAWlex
"""

a = int(input("ввести делимое: "))
b = int(input("ввести делитель: "))
try:
  x=a//b
  print(x)
except ZeroDivisionError:
    print("На ноль делить нельзя!")
finally:
  print("сработал finally")
  print(type(x))

import random
x = random.randint(0,100)
print(x)

import random
arr = [0, 10, 25, 40, 100, "test1", "test2", "test3"]
print ("Случайное число из списка: ", random.choice(arr))

import random
arr = [0, 10, 25, 40, 100, "test1", "test2", "test3"]
# print ("Случайное число из списка: ", random.choice(arr))
print(arr[5], arr[0])
print(arr)
print(len(arr))
print(type(arr))

import random
y = random.random()
x = "Прювет"
print(y)
print(type(y))
print(type(x))
print(len(x))

import random

y = random.uniform(1.5, 2.5)
print(y)

import random
a = random.randint(1,6)
b = random.randint(1,6)
c = random.randint(1,6)
d = random.randint(1,6)
total = a+b+c+d
print ("бросок 1-", a,"бросок 2-",b , "бросок 3-",c ,"бросок 1-",d, "общая сумма ", total )

import random
k = 4
y = []
while k != 0:
   x= random.randint(1,6)
   k -= 1
   y.append(x)
   print (y)

print ("Сумма 4  бросков", sum(y))

import random
k = 4
y = []
total = 0
while k != 0:
   x= random.randint(1,6)
   k -= 1
   y.append(x)
   print (y)

for i in y:
  print ("Значение i - ", i, "Значение total - ", total)
  total += i

print ("Сумма 4-х  бросков", total)

import random

chars = '+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
length = input('Длина пароля:' + "\n")
password = ""

try:
  length = int(length)
  for i  in range(length):
    password += random.choice(chars)

  print ("Пароль:", password)

except ValueError:
    print("введены буквы! нужны цифры")
finally:
  password = ""
  length = input('Длина пароля:' + "\n")
  length = int(length)
  for i  in range(length):
    password += random.choice(chars)
    
  print ("Пароль:", password)
